image: node:8.9.1

stages:
  - build
  - deploy

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build

production:
  type: deploy
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=food-bank-management-front-end --api-key=$HEROKU_API_KEY
  only:
    - master