
export const FETCH_COLLECTION_POINTS = 'FETCH_COLLECTION_POINTS';
export const FETCH_CHAINS = 'FETCH_CHAINS';
export const FETCH_CITIES = 'FETCH_CITIES';
export const FETCH_TEAM_LEADERS = 'FETCH_TEAM_LEADERS';
export const FETCH_TEAM_LEADERS_COLLECTION_POINT_LIST = 'FETCH_TEAM_LEADERS_COLLECTION_POINT_LIST';
